name 'polyfill'
maintainer 'TPMM'
maintainer_email 'Chef-Marketing@progress.com'
license 'All Rights Reserved'
description 'Installs/Configures polyfill'
version '0.2.0'
chef_version '>= 16.0'

issues_url 'https://github.com/chef-cft/polyfill/issues'
source_url 'https://github.com/chef-cft/polyfill'
