---
name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  markdownlint:
    uses: chef/github-workflows/.github/workflows/markdown-lint.yml@main
  yamllint:
    uses: chef/github-workflows/.github/workflows/yaml-lint.yml@main
  cookstylelint:
    uses: chef/github-workflows/.github/workflows/cookstyle-lint.yml@main

  integration:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - rockylinux-8
          - ubuntu-2204
        suite:
          - default
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Dokken
        uses: actionshub/test-kitchen@3.0.0
        env:
          CHEF_VERSION: latest
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
